import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/assets/css/globals.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import NavBar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }

}: {
  params: { locale: string },
  children: React.ReactNode
}) {

  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === "fa" ? "rtl" : "ltr"}>
      <NextIntlClientProvider messages={messages} locale={locale}>
        <body className={inter.className}>
          <NavBar />
          <main className="mt-16">
            {children}
          </main>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
